[package]
name = "rebalancer"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
bigdecimal = { version = "0.4.1", features = ["serde"] }
